// Data shapes for extra product documents (die cuts, carton designs,
// technical data sheets, etc.) attached to a product sheet (SKU).
//
// Unlike ProductSheetData, these files are never generated by the app —
// they are existing files the user already has and just wants to store and
// retrieve, organized by category, per SKU.

export type DocumentCategory =
  | "technical_data_sheet"
  | "die_cut"
  | "carton_design"
  | "other";

export const DOCUMENT_CATEGORIES: { value: DocumentCategory; label: string }[] = [
  { value: "technical_data_sheet", label: "Technical data sheet" },
  { value: "die_cut", label: "Die cut" },
  { value: "carton_design", label: "Design carton" },
  { value: "other", label: "Autre" },
];

export function categoryLabel(category: string): string {
  return DOCUMENT_CATEGORIES.find((c) => c.value === category)?.label ?? category;
}

export interface ProductDocumentData {
  id: string;
  ref: string;
  category: DocumentCategory;
  fileName: string;
  url: string;
  mimeType: string | null;
  fileSize: number | null;
  uploadedAt: string;
}

// Row shape as stored in the Supabase `product_documents` table (snake_case).
export interface ProductDocumentRow {
  id: string;
  ref: string;
  category: string;
  file_name: string;
  storage_path: string;
  mime_type: string | null;
  file_size: number | null;
  uploaded_at: string;
}

export function rowToDocument(row: ProductDocumentRow, publicUrl: string): ProductDocumentData {
  return {
    id: row.id,
    ref: row.ref,
    category: row.category as DocumentCategory,
    fileName: row.file_name,
    url: publicUrl,
    mimeType: row.mime_type,
    fileSize: row.file_size,
    uploadedAt: row.uploaded_at,
  };
}

