#!/bin/bash
set -e
echo "Applying: fix broken links for externally-linked (Drive) documents..."

cat > src/app/api/product-documents/route.ts <<'RTEOF'
import { NextRequest, NextResponse } from "next/server";
import { supabaseAdmin, PRODUCT_DOCUMENTS_BUCKET } from "@/lib/supabaseAdmin";
import {
  DOCUMENT_CATEGORIES,
  rowToDocument,
  type DocumentCategory,
  type ProductDocumentRow,
} from "@/lib/documentTypes";

export const runtime = "nodejs";
export const maxDuration = 30;

const VALID_CATEGORIES = new Set(DOCUMENT_CATEGORIES.map((c) => c.value));

// GET /api/product-documents?ref=<sku ref>
// Lists every extra document (die cut, carton design, technical data
// sheet, etc.) attached to a given product sheet, most recent first.
export async function GET(req: NextRequest) {
  const ref = req.nextUrl.searchParams.get("ref")?.trim() ?? "";
  if (!ref) {
    return NextResponse.json({ error: "Paramètre 'ref' manquant." }, { status: 400 });
  }

  const supabase = supabaseAdmin();
  const { data, error } = await supabase
    .from("product_documents")
    .select("*")
    .eq("ref", ref)
    .order("uploaded_at", { ascending: false });

  if (error) {
    return NextResponse.json({ error: error.message }, { status: 500 });
  }

  const documents = (data as ProductDocumentRow[]).map((row) => {
    // storage_path is usually a path within our own bucket, but for documents
    // imported from an external source (e.g. an existing Drive file linked
    // as-is rather than re-hosted) it can be a full URL — pass those through
    // unchanged instead of mangling them through getPublicUrl.
    if (row.storage_path.startsWith("http://") || row.storage_path.startsWith("https://")) {
      return rowToDocument(row, row.storage_path);
    }
    const { data: pub } = supabase.storage
      .from(PRODUCT_DOCUMENTS_BUCKET)
      .getPublicUrl(row.storage_path);
    return rowToDocument(row, pub.publicUrl);
  });

  return NextResponse.json({ documents });
}

// POST /api/product-documents
// multipart/form-data with:
//   - "ref": the SKU reference the document belongs to (must already exist
//     in product_sheets)
//   - "category": one of DOCUMENT_CATEGORIES
//   - "file": the file being stored (never generated by the app — this is
//     purely a place to file away documents the user already has)
export async function POST(req: NextRequest) {
  const form = await req.formData();
  const ref = (form.get("ref") as string | null)?.trim() ?? "";
  const category = (form.get("category") as string | null)?.trim() ?? "";
  const file = form.get("file");

  if (!ref) {
    return NextResponse.json({ error: "Paramètre 'ref' manquant." }, { status: 400 });
  }
  if (!VALID_CATEGORIES.has(category as DocumentCategory)) {
    return NextResponse.json({ error: "Catégorie de document invalide." }, { status: 400 });
  }
  if (!(file instanceof File) || file.size === 0) {
    return NextResponse.json({ error: "Aucun fichier reçu." }, { status: 400 });
  }

  const supabase = supabaseAdmin();

  // Verify the SKU exists before filing a document under it.
  const { data: sheet, error: sheetError } = await supabase
    .from("product_sheets")
    .select("ref")
    .eq("ref", ref)
    .maybeSingle();
  if (sheetError) {
    return NextResponse.json({ error: sheetError.message }, { status: 500 });
  }
  if (!sheet) {
    return NextResponse.json(
      { error: `Aucune fiche produit trouvée pour la référence "${ref}".` },
      { status: 404 }
    );
  }

  const safeName = file.name.replace(/[^a-zA-Z0-9._-]+/g, "_");
  const storagePath = `${ref}/${category}/${Date.now()}-${safeName}`;
  const bytes = Buffer.from(await file.arrayBuffer());

  const { error: uploadError } = await supabase.storage
    .from(PRODUCT_DOCUMENTS_BUCKET)
    .upload(storagePath, bytes, { contentType: file.type || "application/octet-stream" });
  if (uploadError) {
    return NextResponse.json({ error: uploadError.message }, { status: 500 });
  }

  const insertRow = {
    ref,
    category,
    file_name: file.name,
    storage_path: storagePath,
    mime_type: file.type || null,
    file_size: file.size,
  };

  const { data: inserted, error: insertError } = await supabase
    .from("product_documents")
    // eslint-disable-next-line @typescript-eslint/no-explicit-any
    .insert(insertRow as any)
    .select("*")
    .single();

  if (insertError) {
    return NextResponse.json({ error: insertError.message }, { status: 500 });
  }

  const { data: pub } = supabase.storage
    .from(PRODUCT_DOCUMENTS_BUCKET)
    .getPublicUrl((inserted as ProductDocumentRow).storage_path);

  return NextResponse.json(
    { document: rowToDocument(inserted as ProductDocumentRow, pub.publicUrl) },
    { status: 201 }
  );
}

// DELETE /api/product-documents?id=<document id>
export async function DELETE(req: NextRequest) {
  const id = req.nextUrl.searchParams.get("id")?.trim() ?? "";
  if (!id) {
    return NextResponse.json({ error: "Paramètre 'id' manquant." }, { status: 400 });
  }

  const supabase = supabaseAdmin();

  const { data: existing, error: fetchError } = await supabase
    .from("product_documents")
    .select("storage_path")
    .eq("id", id)
    .maybeSingle();
  if (fetchError) {
    return NextResponse.json({ error: fetchError.message }, { status: 500 });
  }
  if (!existing) {
    return NextResponse.json({ error: "Document introuvable." }, { status: 404 });
  }

  const existingPath = (existing as { storage_path: string }).storage_path;
  // External links (e.g. Drive) were never uploaded to our bucket, so there's
  // nothing to remove from Storage — just drop the database row below.
  if (!existingPath.startsWith("http://") && !existingPath.startsWith("https://")) {
    const { error: removeError } = await supabase.storage
      .from(PRODUCT_DOCUMENTS_BUCKET)
      .remove([existingPath]);
    if (removeError) {
      return NextResponse.json({ error: removeError.message }, { status: 500 });
    }
  }

  const { error: deleteError } = await supabase
    .from("product_documents")
    .delete()
    .eq("id", id);
  if (deleteError) {
    return NextResponse.json({ error: deleteError.message }, { status: 500 });
  }

  return NextResponse.json({ ok: true });
}

RTEOF

git add -A
git status
echo "Done. Review the diff, then: git commit -m \"Fix Drive-linked document URLs (was 404ing)\" && git push"
