import type { ProductSheetData } from "@/lib/types";

function esc(v: string | null | undefined): string {
  return v === undefined || v === null || v === "" ? "—" : v;
}

/**
 * Visual rendering of a single product datasheet ("la fiche").
 *
 * This is the single source of truth for the sheet layout: it is used for
 * the live preview in the creation form, the read-only modal in the
 * directory, and — via ReactDOMServer.renderToStaticMarkup on the server —
 * for the PDF generated by Puppeteer. Keeping one component means the PDF
 * can never drift from what the user sees on screen.
 */
export default function ProductSheetView({ data }: { data: ProductSheetData }) {
  return (
    <div className="sheet">
      <div className="sheet-header">
        <div className="sheet-brand">
                              <img src="/logo.png" alt="MBA Green" className="sheet-logo" />
        </div>
        <div className="sheet-titles">
          <div className="fr">{esc(data.nameFr)}</div>
          <div className="en">{esc(data.nameEn)}</div>
        </div>
      </div>

      <div className="sheet-body">
        <div className="sheet-left">
          <div className="sheet-imgbox">
            {data.imageUrl ? (
              // eslint-disable-next-line @next/next/no-img-element
              <img src={data.imageUrl} alt={data.ref} />
            ) : (
              <div className="ph">
                Visuel produit
                <br />à insérer
              </div>
            )}
          </div>
          <div className="sheet-navlabel">
            <div className="fr">
              Caractéristiques
              <br />
              produit
            </div>
            <div className="en">Product specifications</div>
          </div>
          <div className="sheet-navlabel">
            <div className="fr">Conditionnement</div>
            <div className="en">Packaging</div>
          </div>
          <div className="sheet-navlabel">
            <div className="fr">
              Caractéristiques
              <br />
              conditionnement
            </div>
            <div className="en">Packaging specifications</div>
          </div>
        </div>

        <div className="sheet-right">
          <div className="idtable">
            <div className="idrow">
              <div className="k">Référence MBA Green</div>
              <div className="v">{esc(data.ref)}</div>
            </div>
            <div className="idrow">
              <div className="k">EAN carton / Box gencode</div>
              <div className="v">{esc(data.eanBox)}</div>
            </div>
            <div className="idrow">
              <div className="k">EAN UVC / Bag gencode</div>
              <div className="v">{esc(data.eanUvc)}</div>
            </div>
            <div className="idrow">
              <div className="k">Nomenclature douanière / Custom code</div>
              <div className="v">{esc(data.customCode)}</div>
            </div>
          </div>

          <div className="specblock">
            <div className="specblock-title">Produit / Product</div>
            <div className="specrow">
              <div className="k">Matière / Material</div>
              <div className="v">{esc(data.material)}</div>
            </div>
            <div className="specrow">
              <div className="k">Capacité / Capacity</div>
              <div className="v">{esc(data.capacity)}</div>
            </div>
            <div className="specrow">
              <div className="k">Hauteur / Height</div>
              <div className="v">{esc(data.height)}</div>
            </div>
            <div className="specrow">
              <div className="k">Diamètre / Diameter</div>
              <div className="v">{esc(data.diameter)}</div>
            </div>
            <div className="specrow">
              <div className="k">Longueur / Length</div>
              <div className="v">{esc(data.length)}</div>
            </div>
            <div className="specrow">
              <div className="k">Gusset</div>
              <div className="v">{esc(data.gusset)}</div>
            </div>
            <div className="specrow">
              <div className="k">Largeur / Width</div>
              <div className="v">{esc(data.width)}</div>
            </div>
            <div className="specrow">
              <div className="k">Poids net / Net weight</div>
              <div className="v">{esc(data.netWeight)}</div>
            </div>
          </div>

          <div className="specblock">
            <div className="specblock-title">UVC / Sales unit</div>
            <div className="specrow">
              <div className="k">Pièces par UVC</div>
              <div className="v">{esc(data.unitsPerUvc)}</div>
            </div>
            <div className="specrow">
              <div className="k">Poids net UVC</div>
              <div className="v">{esc(data.uvcWeight)}</div>
            </div>
          </div>

          <div className="specblock">
            <div className="specblock-title">Carton / Box</div>
            <div className="specrow">
              <div className="k">Pièces par carton</div>
              <div className="v">{esc(data.unitsPerBox)}</div>
            </div>
            <div className="specrow">
              <div className="k">Dimension carton</div>
              <div className="v">{esc(data.boxDim)}</div>
            </div>
            <div className="specrow">
              <div className="k">Poids brut carton</div>
              <div className="v">{esc(data.boxGross)}</div>
            </div>
            <div className="specrow">
              <div className="k">Poids net carton</div>
              <div className="v">{esc(data.boxNet)}</div>
            </div>
            <div className="specrow">
              <div className="k">Volume carton</div>
              <div className="v">{esc(data.boxVolume)}</div>
            </div>
          </div>

          <div className="specblock">
            <div className="specblock-title">Palette / Pallet</div>
            <div className="specrow">
              <div className="k">Pièces par palette</div>
              <div className="v">{esc(data.unitsPerPallet)}</div>
            </div>
            <div className="specrow">
              <div className="k">Cartons par palette</div>
              <div className="v">{esc(data.boxesPerPallet)}</div>
            </div>
            <div className="specrow">
              <div className="k">Couches par palette</div>
              <div className="v">{esc(data.layersPerPallet)}</div>
            </div>
            <div className="specrow">
              <div className="k">Cartons par couche</div>
              <div className="v">{esc(data.boxesPerLayer)}</div>
            </div>
            <div className="specrow">
              <div className="k">Hauteur palette</div>
              <div className="v">{esc(data.palletHeight)}</div>
            </div>
            <div className="specrow">
              <div className="k">Poids palette</div>
              <div className="v">{esc(data.palletWeight)}</div>
            </div>
            <div className="specrow">
              <div className="k">Volume palette</div>
              <div className="v">{esc(data.palletVolume)}</div>
            </div>
          </div>

          <div className="tolerance">Tolérance / Tolerance : {esc(data.tolerance)}</div>
        </div>
      </div>

      <div className="sheet-footer">
        <div className="ref">{esc(data.ref)}</div>
        <div className="url">MBAGREEN.NET</div>
      </div>
    </div>
  );
}
