"use client";

import { useCallback, useEffect, useRef, useState } from "react";
import {
  DOCUMENT_CATEGORIES,
  type DocumentCategory,
  type ProductDocumentData,
} from "@/lib/documentTypes";

const ACCEPT =
  ".pdf,.png,.jpg,.jpeg,.webp,.gif,.ai,.eps,.dwg,.dxf,.zip,application/pdf,image/*";

function formatSize(bytes: number | null): string {
  if (!bytes) return "";
  if (bytes < 1024) return `${bytes} o`;
  if (bytes < 1024 * 1024) return `${Math.round(bytes / 1024)} Ko`;
  return `${(bytes / (1024 * 1024)).toFixed(1)} Mo`;
}

function formatDate(iso: string): string {
  try {
    return new Date(iso).toLocaleDateString("fr-FR", {
      day: "2-digit",
      month: "2-digit",
      year: "numeric",
    });
  } catch {
    return "";
  }
}

// Pure fetch helper (no setState) so it can be safely called both from the
// mount effect and from event handlers without tripping the
// react-hooks/set-state-in-effect rule.
async function fetchDocuments(skuRef: string): Promise<ProductDocumentData[]> {
  const res = await fetch(`/api/product-documents?ref=${encodeURIComponent(skuRef)}`);
  const json = await res.json();
  if (!res.ok) throw new Error(json.error || "Erreur de chargement.");
  return json.documents ?? [];
}

/**
 * "Documents" panel attached to a product sheet (SKU): lets the user file
 * away and retrieve extra documents (die cuts, carton designs, technical
 * data sheets, etc.) that already exist and are never generated by the
 * app — just uploaded, categorized, and stored per SKU.
 */
export default function ProductDocuments({ skuRef }: { skuRef: string }) {
  const [documents, setDocuments] = useState<ProductDocumentData[]>([]);
  const [loading, setLoading] = useState(true);
  const [category, setCategory] = useState<DocumentCategory>("technical_data_sheet");
  const [dragActive, setDragActive] = useState(false);
  const [uploading, setUploading] = useState(false);
  const [message, setMessage] = useState<string | null>(null);
  const fileInputRef = useRef<HTMLInputElement | null>(null);

  useEffect(() => {
    let cancelled = false;
    fetchDocuments(skuRef)
      .then((docs) => {
        if (!cancelled) setDocuments(docs);
      })
      .catch((e: Error) => {
        if (!cancelled) setMessage(e.message);
      })
      .finally(() => {
        if (!cancelled) setLoading(false);
      });
    return () => {
      cancelled = true;
    };
  }, [skuRef]);

  const reload = useCallback(async () => {
    try {
      setDocuments(await fetchDocuments(skuRef));
    } catch (e) {
      setMessage((e as Error).message);
    }
  }, [skuRef]);

  const uploadFiles = useCallback(
    async (files: FileList | File[]) => {
      const list = Array.from(files);
      if (list.length === 0) return;
      setUploading(true);
      setMessage(null);
      try {
        for (const file of list) {
          const form = new FormData();
          form.set("ref", skuRef);
          form.set("category", category);
          form.set("file", file);
          const res = await fetch("/api/product-documents", { method: "POST", body: form });
          const json = await res.json();
          if (!res.ok) throw new Error(json.error || `Échec de l'envoi de "${file.name}".`);
        }
        await reload();
      } catch (e) {
        setMessage((e as Error).message);
      } finally {
        setUploading(false);
        if (fileInputRef.current) fileInputRef.current.value = "";
      }
    },
    [skuRef, category, reload]
  );

  const handleDelete = useCallback(
    async (id: string) => {
      setDocuments((prev) => prev.filter((d) => d.id !== id));
      try {
        const res = await fetch(`/api/product-documents?id=${encodeURIComponent(id)}`, {
          method: "DELETE",
        });
        if (!res.ok) {
          const json = await res.json();
          throw new Error(json.error || "Échec de la suppression.");
        }
      } catch (e) {
        setMessage((e as Error).message);
        reload();
      }
    },
    [reload]
  );

  const grouped = DOCUMENT_CATEGORIES.map((c) => ({
    ...c,
    items: documents.filter((d) => d.category === c.value),
  }));

  return (
    <div className="docs-panel">
      <h3 className="docs-title">Documents</h3>
      <p className="docs-hint">
        Die cuts, designs cartons, technical data sheets… glissez vos fichiers, ils ne sont pas
        générés par l&apos;app, seulement classés ici par référence.
      </p>

      <div className="docs-upload-row">
        <select
          className="docs-category-select"
          value={category}
          onChange={(e) => setCategory(e.target.value as DocumentCategory)}
          disabled={uploading}
        >
          {DOCUMENT_CATEGORIES.map((c) => (
            <option key={c.value} value={c.value}>
              {c.label}
            </option>
          ))}
        </select>

        <div
          className={`docs-dropzone ${dragActive ? "active" : ""}`}
          onClick={() => fileInputRef.current?.click()}
          onDragOver={(e) => {
            e.preventDefault();
            setDragActive(true);
          }}
          onDragLeave={() => setDragActive(false)}
          onDrop={(e) => {
            e.preventDefault();
            setDragActive(false);
            if (e.dataTransfer.files?.length) uploadFiles(e.dataTransfer.files);
          }}
        >
          {uploading ? "Envoi en cours…" : "Glissez vos fichiers ici ou cliquez pour parcourir"}
          <input
            ref={fileInputRef}
            type="file"
            accept={ACCEPT}
            multiple
            style={{ display: "none" }}
            onChange={(e) => {
              if (e.target.files?.length) uploadFiles(e.target.files);
            }}
          />
        </div>
      </div>

      {message && <div className="docs-message">{message}</div>}

      {loading ? (
        <div className="docs-empty">Chargement…</div>
      ) : (
        <div className="docs-groups">
          {grouped.map((g) => (
            <div className="docs-group" key={g.value}>
              <div className="docs-group-title">
                {g.label} <span className="docs-count">({g.items.length})</span>
              </div>
              {g.items.length === 0 ? (
                <div className="docs-empty">Aucun fichier</div>
              ) : (
                <ul className="docs-list">
                  {g.items.map((d) => (
                    <li className="docs-item" key={d.id}>
                      <a href={d.url} target="_blank" rel="noopener noreferrer" className="docs-item-name">
                        {d.fileName}
                      </a>
                      <span className="docs-item-meta">
                        {formatSize(d.fileSize)} · {formatDate(d.uploadedAt)}
                      </span>
                      <button
                        type="button"
                        className="docs-item-delete"
                        onClick={() => handleDelete(d.id)}
                        aria-label={`Supprimer ${d.fileName}`}
                      >
                        ✕
                      </button>
                    </li>
                  ))}
                </ul>
              )}
            </div>
          ))}
        </div>
      )}
    </div>
  );
}

